export const NOTAS_LIST_REQUEST = "NOTAS_LIST_REQUEST";

export const NOTAS_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";

export const NOTAS_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const NOTAS_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";

export const NOTAS_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";

export const NOTAS_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const NOTAS_EDIT_REQUEST = "PRODUCT_EDIT_REQUEST";

export const NOTAS_EDIT_SUCCESS = "NOTAS_EDIT_SUCCESS";

export const NOTAS_EDIT_FAIL = "NOTAS_EDIT_FAIL";

export const NOTAS_LIST_FILTER = "NOTAS_LIST_FILTER";

export const NOTAS_DELETE_SUCCESS = "NOTAS_DELETE_SUCCESS"